### ISSUE TITLE
Download failes

### ISSUE THREAD

**Issue by NE3D** [JuanJakobo/Pocketbook-Die-Zeit#1]
Thanks for this great project! I am using it with great joy. But unfortunately since 4 weeks I have not been able to download the latest editions (as of DIE ZEIT 22/2021). Is this a knows issue or just something with my PocketBoot..? Thanks in advance!

**Comment by JuanJakobo** [comment]
Hey @NE3D,

Thanks for the hint! Since like half a year ago I do no longer use my Pocketbook to read die Zeit.
Anyway they just changed their URL, so I was able to fix it.
I added some other things, that I wanted to add for a long time and had mostly already included in other projects.
Using the new version, it should work again. if it does not, I will have a look at it again. :)
https://github.com/JuanJakobo/Pocketbook-Die-Zeit/releases/tag/0.3

**Comment by NE3D** [comment]
I just updated and it works. Awesome! Thank you!
